### ISSUE TITLE
large genome

### ISSUE THREAD

**Issue by xunxun66** [Sentieon/sentieon-google-genomics#3]
Dear sir,  
I wonder if sentieon can support larger genome sequence which chromosome length is larger than 700Mb?
in my case,  
1. my chrom length ≈ 738Mb, but the result gvcf endswith 536997358bp, no result between 537Mb and 738Mb
2. or my chrom length ≈ 738Mb, the result gvcf endswith 738Mb, but just less than 5 SNPs between 537Mb and 738Mb

**Comment by DonFreed** [comment]
Could you let us know which version of the software you are using along with the full command line? Could you also provide some information on the source of the reference genome you are using?

This question might be better handled through our standard support channels. You can reach our support team at [support@sentieon.com](mailto:support@sentieon.com).

**Comment by xunxun66** [comment]
> 

Dear sir, I have emailed the [support@sentieon.com](mailto:support@sentieon.com) 
And below is a detailed description of this problem:
1. reference genome length info
chr1	759857066
chr2	727270232
chr3	626048174
chr4	539822115
chr5	493934695
some chromosome length larger than 512Mb, which gatk can deal with csi index



2. sentieon version

Sentieon 202010.02

3. calling snps
sentieon driver -r ref.fa -t 10 -i sample.deduped.bam --algo DNAscope --emit_mode gvcf --var_type snp,indel sample_DNAscope.GVCF.gz

with csi index: 
Error: Failed to load index file sample.deduped.bai, No such file or directory

with bai index: 
the result gvcf info abnormal like the figure below
![image](https://user-images.githubusercontent.com/50433962/176335806-89831d76-02d1-4c03-b1c6-60516e9809ab.png)
![image](https://user-images.githubusercontent.com/50433962/176335824-0598cb58-6feb-4fba-9cff-e622a0a71e19.png)

**Comment by DonFreed** [comment]
Thanks for the additional details. I think our support team has answered your questions through email so I'm closing this issue. Please let me know if that's not the case.
